# Generated by Django 4.2.1 on 2023-07-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='preparition_steps',
            new_name='preparation_steps',
        ),
    ]
