# Generated by Django 4.2.1 on 2023-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_name_recipe_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default='prato', max_length=65),
            preserve_default=False,
        ),
    ]
